name: Node.js CI

on: push

env:
  node-version: 12.20.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-modules-${{ env.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ env.node-version }}-${{ hashFiles('package-lock.json') }}
            node-modules-${{ env.node-version }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint the source code
        run: npm run lint

  pack:
    name: Pack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-modules-${{ env.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ env.node-version }}-${{ hashFiles('package-lock.json') }}
            node-modules-${{ env.node-version }}-

      - name: Install dependencies
        run: npm ci

      - name: Package the WebExtension archive
        run: npm run pack
